[package]
name = "dawnslayer"
version = "0.1.0"
authors = ["Daichi Shinozaki <dseg@shield.jp>"]

[dependencies]
rocksdb = "0.7.0"
# fastpbkdf2 = "0.1.0"
jsonrpc-http-server = "7.0.1"
protobuf = "1.4.1"